version: '3.8'

services:
  go-ms:
    network_mode: bridge
    build:
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - DB_HOST=127.0.0.1
      - DB_NAME=gopostgres
      - DB_USER=postgres
      - DB_PASSWORD=alex
      - DB_PORT=5432
      - LOGFILE=peopleservice.log
      - LOGPATH=../logs/
      - ENV="DEV"